### PR TITLE
marc_spec supports nested_arrays and subspecs

### PR DESCRIPTION
**Pull request by cKlee**

### CODE REVIEW

**Comment by cKlee** [comment]
Argh! I forgot to fix the POD... To be continued...

**Comment by phochste** [comment]
Ok take your time. I'm out for the rest of the week and will check again next monday

**Comment by cKlee** [comment]
Ok! POD is adjusted.

**Comment by cKlee** [comment]
@phochste ready to merge

**Comment by phochste** [comment]
thanks

**Pull request merged**
